language: python
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"
 
before_script:
  - "sudo mkdir /usr/lib/python3.4/site-packages/"
  - "pip3 install setuptools"
 
script: sudo python3 setup.py install && ./run_tests.sh
